window.QUARTZ_CONFIG = {
  SUPABASE_URL: "https://zoernpogmvpengogzrft.supabase.co",
  SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpvZXJucG9nbXZwZW5nb2d6cmZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODk2NTQ5MTEsImV4cCI6MjEwNTIzMDkxMX0.A3OogiljpRF28zsqWBS6cGaAnJ0Bb69yQtZoUpp_umM"
};
